require('keybindings/general')
-- vim.cmd([[source /home/rstar284/.config/nvim/lua/keybindings/general.lua]])
require('keybindings/tabs')
-- vim.cmd([[source /home/rstar284/.config/nvim/lua/keybindings/tabs.lua]])
require('keybindings/spellcheck')
--vim.cmd([[source /home/rstar284/.config/nvim/lua/keybindings/spellcheck.lua]])
require('keybindings/buffers')
-- vim.cmd([[source /home/rstar284/.config/nvim/lua/keybindings/buffers.lua]])
require('keybindings/terminal')
-- vim.cmd([[source /home/rstar284/.config/nvim/lua/keybindings/terminal.lua]])
