format = """
$username@$hostname\
$directory \
$git_branch\
$git_status\
$character\
"""

continuation_prompt = '[λ > ](bold blue)'

[character]
success_symbol = "[λ](bold #7aa2f7)"
error_symbol = "[λ](bold #7aa2f7)"

[username]
format = "[$user]($style)"
show_always = true
style_root = "bold red"
style_user = "#2ac3de"

[hostname]
format = "[$hostname]($style) "
style = "#2ac3de"
ssh_only = false

[directory]
format = "[$path]($style) "
style = "#7dcfff"

[git_branch]
format = "[$symbol$branch]($style) "
