export EDITOR='nvim'
export ARCHFLAGS="-arch x86_64"
export PATH="/home/rstar284/.local/share/gem/ruby/3.0.0/bin:/home/rstar284/.deta/bin:$PATH"
export GCM_CREDENTIAL_STORE=cache
export FZF_DEFAULT_OPTS='
    --exact
    --reverse
    --border=rounded
    --cycle
    --height=50%
    --info=hidden
    --prompt=❯\ 
    --pointer=➜
    --color=16
    --color=bg:-1,bg+:8
    --color=fg:-1,fg+:-1
    --color=hl:2,hl+:2
    --color=prompt:2
    --color=pointer:4
    --color=gutter:-1
    --color=marker:11
    --color=spinner:6
    --color=border:8'
export _JAVA_AWT_WM_NONREPARENTING=1
export QT_QPA_PLATFORM=wayland
export MOZ_ENABLE_WAYLAND=1
export MOZ_WEBRENDER=1
export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=sway
export GTK_USE_PORTAL=0
export ZPLUGINDIR=${ZPLUGINDIR:-${ZDOTDIR:-$HOME/.config/zsh}/plugins}

alias cpf='wl-clip < '
alias lsl='ls -Al'
alias ls='ls -A'
alias wshowkeys='wshowkeys -b="#1c1b22" -a bottom -F="Hack Nerd Font Regular 20"'
alias plugins='ls $ZPLUGINDIR'

if [[ ! -d $ZPLUGINDIR/zsh_unplugged ]]; then
  git clone --quiet https://github.com/mattmc3/zsh_unplugged $ZPLUGINDIR/zsh_unplugged
fi
source $ZPLUGINDIR/zsh_unplugged/zsh_unplugged.plugin.zsh

repos=(
    romkatv/zsh-defer
    zsh-users/zsh-completions
    zsh-users/zsh-syntax-highlighting
    zsh-users/zsh-autosuggestions
)

plugin-load $repos

function plugin-update {
  ZPLUGINDIR=${ZPLUGINDIR:-$HOME/.config/zsh/plugins}
  for d in $ZPLUGINDIR/*/.git(/); do
    echo "Updating ${d:h:t}..."
    command git -C "${d:h}" pull --ff --recurse-submodules --depth 1 --rebase --autostash
  done
}

function plugin-compile {
  ZPLUGINDIR=${ZPLUGINDIR:-$HOME/.config/zsh/plugins}
  autoload -U zrecompile
  local f
  for f in $ZPLUGINDIR/**/*.zsh{,-theme}(N); do
    zrecompile -pq "$f"
  done
}

function short () {
    curl -X POST https://link.what-is.ml/api/new -H "Content-Type: application/json" -d "{\"url\": \"$1\"}" | xclip -sel clip
}

if [ -z $DISPLAY ] && [ "$(tty)" = "/dev/tty1" ]; then
    eval $(gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh | sed 's/^\(.*\)/export \1/g')
    exec sway
fi

(cat ~/.cache/wal/sequences &)
source ~/.cache/wal/colors-tty.sh
source /usr/share/nvm/init-nvm.sh
neofetch --ascii "$( cowsay -f tux -W 30 "I use Arch btw.")"
eval $(starship init zsh)
