require("presence"):setup({
    auto_update         = true,
    neovim_image_text   = "The One True Text Editor",
     main_image          = "neovim",
     client_id           = "793271441293967371",
     debounce_timeout    = 10,
     enable_line_number  = true,
     buttons             = true,
     editing_text        = "Suffering with %s",
     file_explorer_text  = "Browsing %s",
     git_commit_text     = "Committing changes",
     plugin_manager_text = "Managing plugins",
     workspace_text      = "Working on %s",
     line_number_text    = "Line %s out of %s",
})
